"""empty message

Revision ID: 435da8ebe009
Revises: 
Create Date: 2023-08-09 13:50:50.915486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435da8ebe009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromUser', sa.Integer(), nullable=True),
    sa.Column('toUser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fromUser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['toUser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('typingText', sa.Text(), nullable=False),
    sa.Column('wordCount', sa.Integer(), nullable=False),
    sa.Column('characterCount', sa.Integer(), nullable=False),
    sa.Column('noSpaceCharacterCount', sa.Integer(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textId', sa.Integer(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('mistakes', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('kpm', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['textId'], ['texts.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('texts')
    op.drop_table('friends')
    op.drop_table('users')
    # ### end Alembic commands ###
